version: "3.7"

services:
  node:
    container_name: node-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.development
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    entrypoint: "tail -f /dev/null"

  redis:
    container_name: ${REDIS_HOST}
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env.development
    command: redis-server --save 20 1 --loglevel warning
