FROM docker.io/node:16

WORKDIR /usr/src/app
USER 0
RUN apt update
RUN apt install wget git bash -y
RUN npm i -g @nestjs/cli
USER 1000
RUN bash -c "$(wget https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"